# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use a Node.js image with TypeScript support
FROM node:20-alpine AS builder

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to install dependencies
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application source code
COPY . .

# Compile TypeScript to JavaScript
RUN npm run build

# Set executable permissions on necessary scripts
RUN chmod +x build/index.js
RUN chmod +x build/scripts/setup-google-env.js

# Use a lightweight Node.js image for production
FROM node:20-alpine AS production

# Set the working directory inside the container
WORKDIR /app

# Copy the compiled build files and node_modules from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/config ./config

# Expose the port that the app runs on
EXPOSE 3000

# Set the entrypoint command to start the server
ENTRYPOINT ["node", "build/index.js"]