#!/usr/bin/env node
// Sync version from package.json → server.json + mcpb/manifest.json + src/version.ts
// and gate the release on registry-side validations we've actually hit:
//   - server.json must have a non-empty `description` ≤ 100 chars (MCP Registry).
//   - package.json must declare `mcpName` matching server.json's `name` (MCP
//     Registry ownership check rejects the npm package otherwise).
// Failing here is much cheaper than failing in `mcp-publisher publish`.
const fs = require('fs');
const pkg = require('../package.json');
const version = pkg.version;

const errors = [];

for (const file of ['server.json', 'mcpb/manifest.json']) {
  if (!fs.existsSync(file)) continue;
  const data = JSON.parse(fs.readFileSync(file, 'utf-8'));
  data.version = version;
  if (data.packages) data.packages.forEach(p => p.version = version);
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
  console.log(`  ${file} → ${version}`);
}

// Stamp src/version.ts so the runtime knows its own version
const versionTs = `// Auto-generated by \`make version-stamp\`. Do not edit manually.\nexport const VERSION = '${version}';\n`;
fs.writeFileSync('src/version.ts', versionTs);
console.log(`  src/version.ts → ${version}`);

// --- Registry pre-flight checks ---

if (fs.existsSync('server.json')) {
  const server = JSON.parse(fs.readFileSync('server.json', 'utf-8'));
  const desc = server.description;
  if (typeof desc !== 'string' || desc.length === 0) {
    errors.push('server.json: top-level `description` is required and must be non-empty (registry rejects with 422 otherwise).');
  } else if (desc.length > 100) {
    errors.push(`server.json: \`description\` is ${desc.length} chars; registry limit is 100. Trim it.`);
  }

  // Each npm package in server.json must be self-declared via package.json's
  // `mcpName` matching server.json's top-level `name`.
  if (Array.isArray(server.packages)) {
    for (const p of server.packages) {
      if (p.registryType === 'npm' && p.identifier === pkg.name) {
        if (pkg.mcpName !== server.name) {
          errors.push(
            `package.json: \`mcpName\` must equal server.json \`name\` (got ${JSON.stringify(pkg.mcpName)}, want ${JSON.stringify(server.name)}). Registry rejects the npm package otherwise.`,
          );
        }
      }
    }
  }
}

if (errors.length > 0) {
  console.error('');
  console.error('Registry pre-flight failed:');
  for (const e of errors) console.error('  • ' + e);
  process.exit(1);
}
