#!/usr/bin/env node
/**
 * Writes the version from package.json into src/version.ts.
 *
 * Single definition, called by BOTH `npm run version-stamp` and the Makefile's
 * `version-stamp` target. It used to exist only as an inline `node -e` in the
 * Makefile, which meant `npm run build` — and therefore `prepublishOnly` — did not
 * stamp at all: publishing outside `make publish-all` shipped a build carrying the
 * PREVIOUS version, with prepublishOnly's presence making it look handled.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolve } from 'node:path';

const ROOT = fileURLToPath(new URL('..', import.meta.url));
const { version } = JSON.parse(readFileSync(resolve(ROOT, 'package.json'), 'utf8'));

writeFileSync(
  resolve(ROOT, 'src/version.ts'),
  '// Auto-generated by `npm run version-stamp`. Do not edit manually.\n' +
  `export const VERSION = '${version}';\n`,
);

console.log(`  src/version.ts → ${version}`);
