#!/usr/bin/env node
// Sync version from package.json → server.json + mcpb/manifest.json + src/version.ts
const fs = require('fs');
const version = require('../package.json').version;

for (const file of ['server.json', 'mcpb/manifest.json']) {
  if (!fs.existsSync(file)) continue;
  const data = JSON.parse(fs.readFileSync(file, 'utf-8'));
  data.version = version;
  if (data.packages) data.packages.forEach(p => p.version = version);
  fs.writeFileSync(file, JSON.stringify(data, null, 2) + '\n');
  console.log(`  ${file} → ${version}`);
}

// Stamp src/version.ts so the runtime knows its own version
const versionTs = `// Auto-generated by \`make version-stamp\`. Do not edit manually.\nexport const VERSION = '${version}';\n`;
fs.writeFileSync('src/version.ts', versionTs);
console.log(`  src/version.ts → ${version}`);
