name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test
      env:
        GOOGLE_CLIENT_ID: test-id
        GOOGLE_CLIENT_SECRET: test-secret
        CONFIG_DIR: ./test-config
        WORKSPACE_BASE_PATH: ./test-workspace

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    # Temporarily disabled Docker build tests
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Test Docker build
    #   uses: docker/build-push-action@v5
    #   with:
    #     context: .
    #     push: false
    #     load: true
    #     tags: google-workspace-mcp:test
    #     no-cache: true

    # - name: Test Docker image
    #   run: |
    #     docker run --rm \
    #       -e GOOGLE_CLIENT_ID=test-id \
    #       -e GOOGLE_CLIENT_SECRET=test-secret \
    #       -e LOG_MODE=strict \
    #       google-workspace-mcp:test --version

  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint
